export const WORKSPACE_MOVE_TYPES_PATH = '.cobblemon-schema-tools/move-types.d.ts';

export const WORKSPACE_MOVE_TYPES_CONTENT = `// Generated by Cobblemon Schema Tools.
// This file is only needed when "Use Typescript for Moves?" is enabled.

export type MoveCategory = 'Physical' | 'Special' | 'Status';
export type MoveTarget =
  | 'adjacentAlly'
  | 'adjacentAllyOrSelf'
  | 'adjacentFoe'
  | 'all'
  | 'allAdjacent'
  | 'allAdjacentFoes'
  | 'allies'
  | 'allySide'
  | 'allyTeam'
  | 'any'
  | 'foeSide'
  | 'normal'
  | 'randomNormal'
  | 'scripted'
  | 'self';

export type MoveFlag =
  | 'allyanim'
  | 'bypasssub'
  | 'bite'
  | 'bullet'
  | 'cantusetwice'
  | 'charge'
  | 'contact'
  | 'dance'
  | 'defrost'
  | 'distance'
  | 'failcopycat'
  | 'failencore'
  | 'failinstruct'
  | 'failmefirst'
  | 'failmimic'
  | 'futuremove'
  | 'gravity'
  | 'heal'
  | 'metronome'
  | 'mirror'
  | 'mustpressure'
  | 'noassist'
  | 'nonsky'
  | 'noparentalbond'
  | 'nosleeptalk'
  | 'pledgecombo'
  | 'powder'
  | 'protect'
  | 'pulse'
  | 'punch'
  | 'recharge'
  | 'reflectable'
  | 'slicing'
  | 'snatch'
  | 'sound'
  | 'wind';

export type StatID = 'atk' | 'def' | 'spa' | 'spd' | 'spe' | 'accuracy' | 'evasion';
export type StatIDExceptHP = 'atk' | 'def' | 'spa' | 'spd' | 'spe';
export type StatusCode = 'brn' | 'par' | 'slp' | 'frz' | 'psn' | 'tox';
export type SelfSwitchType = 'copyvolatile' | 'shedtail' | boolean;
export type SelfdestructType = 'always' | 'ifHit' | boolean;

export type SparseBoostsTable = Partial<Record<StatID, number>>;
export type MoveFlags = Partial<Record<MoveFlag, 1>>;

export interface Battle {
  [key: string]: unknown;
}

export interface Pokemon {
  [key: string]: unknown;
}

export interface Side {
  [key: string]: unknown;
}

export interface Effect {
  [key: string]: unknown;
}

export interface Ability {
  [key: string]: unknown;
}

export interface ActiveMove extends MoveData {
  [key: string]: unknown;
}

export interface HitEffect {
  boosts?: SparseBoostsTable | null;
  status?: string;
  volatileStatus?: string;
  sideCondition?: string;
  slotCondition?: string;
  pseudoWeather?: string;
  terrain?: string;
  weather?: string;
}

export interface SecondaryEffect extends HitEffect {
  chance?: number;
  ability?: Ability;
  dustproof?: boolean;
  kingsrock?: boolean;
  self?: HitEffect;
}

export interface ConditionData {
  duration?: number;
  [key: \`on\${string}\`]: unknown;
}

export interface MoveEventMethods {
  basePowerCallback?: (this: Battle, pokemon: Pokemon, target: Pokemon, move: ActiveMove) => number | false | null;
  beforeMoveCallback?: (this: Battle, pokemon: Pokemon, target: Pokemon | null, move: ActiveMove) => boolean | void;
  beforeTurnCallback?: (this: Battle, pokemon: Pokemon, target: Pokemon) => void;
  damageCallback?: (this: Battle, pokemon: Pokemon, target: Pokemon) => number | false;
  priorityChargeCallback?: (this: Battle, pokemon: Pokemon) => void;
  onDisableMove?: (this: Battle, pokemon: Pokemon) => void;
  onAfterHit?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => void;
  onAfterSubDamage?: (this: Battle, damage: number, target: Pokemon, source: Pokemon, move: ActiveMove) => void;
  onAfterMoveSecondarySelf?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => void;
  onAfterMoveSecondary?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => void;
  onAfterMove?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => void;
  onDamagePriority?: number;
  onDamage?: (this: Battle, damage: number, target: Pokemon, source: Pokemon, effect: Effect) => number | boolean | null | void;
  onBasePower?: (this: Battle, basePower: number, pokemon: Pokemon, target: Pokemon, move: ActiveMove) => number | void;
  onEffectiveness?: (this: Battle, typeMod: number, target: Pokemon | null, type: string, move: ActiveMove) => number | void;
  onHit?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => boolean | null | '' | void;
  onHitField?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => boolean | null | '' | void;
  onHitSide?: (this: Battle, side: Side, source: Pokemon, move: ActiveMove) => boolean | null | '' | void;
  onModifyMove?: (this: Battle, move: ActiveMove, pokemon: Pokemon, target: Pokemon | null) => void;
  onModifyPriority?: (this: Battle, priority: number, source: Pokemon, target: Pokemon, move: ActiveMove) => number | void;
  onMoveFail?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => void;
  onModifyType?: (this: Battle, move: ActiveMove, pokemon: Pokemon, target: Pokemon) => void;
  onModifyTarget?: (this: Battle, relayVar: {target: Pokemon}, pokemon: Pokemon, target: Pokemon, move: ActiveMove) => void;
  onPrepareHit?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => boolean | null | '' | void;
  onTry?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => boolean | null | void;
  onTryHit?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => boolean | number | null | '' | void;
  onTryHitField?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => boolean | null | '' | void;
  onTryHitSide?: (this: Battle, side: Side, source: Pokemon, move: ActiveMove) => boolean | null | '' | void;
  onTryImmunity?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => boolean | null | '' | void;
  onTryMove?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => boolean | null | void;
  onUseMoveMessage?: (this: Battle, target: Pokemon, source: Pokemon, move: ActiveMove) => void;
}

export interface MoveData extends HitEffect, MoveEventMethods {
  name: string;
  num?: number;
  condition?: ConditionData;
  basePower: number;
  accuracy: true | number;
  pp: number;
  category: MoveCategory;
  type: string;
  priority: number;
  target: MoveTarget;
  flags: MoveFlags;
  secondary: SecondaryEffect | null;
}
`;
