export const WORKSPACE_MOVE_TYPES_PATH = '.cobblemon-schema-tools/move-types.d.ts';

export const WORKSPACE_MOVE_TYPES_CONTENT = `// Generated by Cobblemon Schema Tools.
// This file is only needed when "Use Typescript for Moves?" is enabled.

export type ID = string;
export type AnyObject = Record<string, unknown>;
export type Nonstandard = string | null;
export type GenderName = 'M' | 'F' | 'N' | '';

export type MoveCategory = 'Physical' | 'Special' | 'Status';
export type MoveTarget =
  | 'adjacentAlly'
  | 'adjacentAllyOrSelf'
  | 'adjacentFoe'
  | 'all'
  | 'allAdjacent'
  | 'allAdjacentFoes'
  | 'allies'
  | 'allySide'
  | 'allyTeam'
  | 'any'
  | 'foeSide'
  | 'normal'
  | 'randomNormal'
  | 'scripted'
  | 'self';

export type MoveFlag =
  | 'allyanim'
  | 'bypasssub'
  | 'bite'
  | 'bullet'
  | 'cantusetwice'
  | 'charge'
  | 'contact'
  | 'dance'
  | 'defrost'
  | 'distance'
  | 'failcopycat'
  | 'failencore'
  | 'failinstruct'
  | 'failmefirst'
  | 'failmimic'
  | 'futuremove'
  | 'gravity'
  | 'heal'
  | 'metronome'
  | 'mirror'
  | 'mustpressure'
  | 'noassist'
  | 'nonsky'
  | 'noparentalbond'
  | 'nosleeptalk'
  | 'pledgecombo'
  | 'powder'
  | 'protect'
  | 'pulse'
  | 'punch'
  | 'recharge'
  | 'reflectable'
  | 'slicing'
  | 'snatch'
  | 'sound'
  | 'wind';

export type StatID = 'atk' | 'def' | 'spa' | 'spd' | 'spe' | 'accuracy' | 'evasion';
export type StatIDExceptHP = 'atk' | 'def' | 'spa' | 'spd' | 'spe';
export type StatusCode = 'brn' | 'par' | 'slp' | 'frz' | 'psn' | 'tox';
export type SelfSwitchType = 'copyvolatile' | 'shedtail' | boolean;
export type SelfdestructType = 'always' | 'ifHit' | boolean;
export type GameType = 'singles' | 'doubles' | 'triples' | 'rotation' | 'multi' | 'freeforall';
export type SideID = 'p1' | 'p2' | 'p3' | 'p4';
export type RequestState = '' | 'move' | 'switch' | 'teampreview';
export type PokemonSlot = number;

export interface StatsTable {
  hp: number;
  atk: number;
  def: number;
  spa: number;
  spd: number;
  spe: number;
}

export interface StatsExceptHPTable {
  atk: number;
  def: number;
  spa: number;
  spd: number;
  spe: number;
}

export type SparseStatsTable = Partial<StatsTable>;
export type SparseBoostsTable = Partial<Record<StatID, number>>;
export type BoostsTable = Record<StatID, number>;
export type MoveFlags = Partial<Record<MoveFlag, 1>>;

export interface EffectState {
  duration?: number;
  [key: string]: unknown;
}

export interface BasicEffect {
  id: ID;
  name: string;
  fullname: string;
  effectType: string;
  exists: boolean;
  num: number;
  gen: number;
  shortDesc: string;
  desc: string;
  isNonstandard: Nonstandard;
  duration?: number;
  noCopy: boolean;
  affectsFainted: boolean;
  status?: ID;
  weather?: ID;
  sourceEffect: string;
}

export interface Effect extends BasicEffect {}

export interface AbilityFlags {
  breakable?: 1;
  cantsuppress?: 1;
  failroleplay?: 1;
  failskillswap?: 1;
  noentrain?: 1;
  noreceiver?: 1;
  notrace?: 1;
  notransform?: 1;
}

export interface Ability extends Effect {
  effectType: 'Ability' | string;
  rating: number;
  suppressWeather: boolean;
  flags: AbilityFlags;
  condition?: ConditionData;
}

export interface Item extends Effect {
  effectType: 'Item' | string;
  fling?: {
    basePower?: number;
    status?: StatusCode;
    volatileStatus?: string;
    condition?: ConditionData;
  };
  forceForme?: string;
  megaStone?: string;
  megaEvolves?: string;
  zMove?: boolean | string;
  zMoveFrom?: string;
  zMoveType?: string;
  onDrive?: string;
  onMemory?: string;
  isBerry?: boolean;
  naturalGift?: {
    basePower: number;
    type: string;
  };
  itemUser?: string[];
}

export interface Nature {
  name: string;
  plus?: StatIDExceptHP;
  minus?: StatIDExceptHP;
}

export interface Species {
  id: ID;
  name: string;
  baseSpecies: string;
  forme: string;
  types: string[];
  baseStats: StatsTable;
  bst?: number;
  weightkg: number;
  heightm: number;
  color?: string;
  abilities: Record<string, string>;
  eggGroups?: string[];
  evos?: string[];
  prevo?: string;
  requiredItems?: string[];
  requiredItem?: string;
  requiredMove?: string;
  gender?: GenderName;
  genderRatio?: {M: number; F: number};
  canHatch?: boolean;
  nfe?: boolean;
  isNonstandard?: Nonstandard;
}

export interface MoveSlot {
  id: ID;
  move: string;
  pp: number;
  maxpp: number;
  target?: string;
  disabled: boolean | string;
  disabledSource?: string;
  used: boolean;
  virtual?: boolean;
}

export interface MoveHitData {
  crit: boolean;
  typeMod: number;
  zBrokeProtect: boolean;
}

export interface HealthDisplay {
  side: SideID;
  secret: string;
  shared: string;
}

export interface ChosenAction {
  choice: 'move' | 'switch' | 'instaswitch' | 'revivalblessing' | 'team' | 'shift' | 'pass';
  pokemon?: Pokemon;
  targetLoc?: number;
  moveid: string;
  move?: ActiveMove;
  target?: Pokemon;
  index?: number;
  side?: Side;
  mega?: boolean | null;
  zmove?: string;
  maxMove?: string;
  terastallize?: string;
  priority?: number;
}

export interface Choice {
  cantUndo: boolean;
  error: string;
  actions: ChosenAction[];
  forcedSwitchesLeft: number;
  forcedPassesLeft: number;
  switchIns: Set<number>;
  zMove: boolean;
  mega: boolean;
  ultra: boolean;
  dynamax: boolean;
  terastallize: boolean;
}

export interface Field {
  battle: Battle;
  weather: ID | '';
  weatherState: EffectState;
  terrain: ID | '';
  terrainState: EffectState;
  pseudoWeather: Record<string, EffectState>;
  getPseudoWeather(status: string | Effect): Effect | null;
  addPseudoWeather(status: string | Effect, source?: Pokemon | null, sourceEffect?: Effect | null): boolean | null;
  removePseudoWeather(status: string | Effect): boolean;
  clearTerrain(): boolean;
  setTerrain(status: string | Effect, source?: Pokemon | null, sourceEffect?: Effect | null): boolean | null;
  isTerrain(...terrain: string[]): boolean;
  clearWeather(): boolean;
  setWeather(status: string | Effect, source?: Pokemon | null, sourceEffect?: Effect | null): boolean | null;
  isWeather(...weather: string[]): boolean;
  suppressingWeather(): boolean;
}

export type GenericMoveCallback = (this: Battle, ...args: any[]) => unknown;
export type GenericConditionCallback = (this: Battle, ...args: any[]) => unknown;
export type ResultMoveCallback = (
  this: Battle,
  target: Pokemon,
  source: Pokemon,
  move: ActiveMove
) => boolean | null | '' | void;
export type ExtResultMoveCallback = (
  this: Battle,
  target: Pokemon,
  source: Pokemon,
  move: ActiveMove
) => boolean | null | number | '' | void;
export type VoidMoveCallback = (
  this: Battle,
  target: Pokemon,
  source: Pokemon,
  move: ActiveMove
) => void;
export type ModifierMoveCallback = (
  this: Battle,
  relayVar: number,
  target: Pokemon,
  source: Pokemon,
  move: ActiveMove
) => number | void;
export type ResultSourceMoveCallback = (
  this: Battle,
  source: Pokemon,
  target: Pokemon,
  move: ActiveMove
) => boolean | null | '' | void;
export type ExtResultSourceMoveCallback = (
  this: Battle,
  source: Pokemon,
  target: Pokemon,
  move: ActiveMove
) => boolean | null | number | '' | void;
export type VoidSourceMoveCallback = (
  this: Battle,
  source: Pokemon,
  target: Pokemon,
  move: ActiveMove
) => void;
export type ModifierSourceMoveCallback = (
  this: Battle,
  relayVar: number,
  source: Pokemon,
  target: Pokemon,
  move: ActiveMove
) => number | void;

export interface HitEffect {
  onHit?: ResultMoveCallback;
  boosts?: SparseBoostsTable | null;
  status?: StatusCode;
  volatileStatus?: string;
  sideCondition?: string;
  slotCondition?: string;
  pseudoWeather?: string;
  terrain?: string;
  weather?: string;
}

export interface SecondaryEffect extends HitEffect {
  chance?: number;
  ability?: Ability;
  dustproof?: boolean;
  kingsrock?: boolean;
  self?: HitEffect;
}

export type ConditionData = {
  duration?: number;
  noCopy?: boolean;
  durationCallback?: (this: Battle, target: Pokemon, source: Pokemon, effect: Effect | null) => number;
  onCopy?: (this: Battle, pokemon: Pokemon) => void;
  onStart?: (this: Battle, target: Pokemon, source: Pokemon, sourceEffect: Effect) => boolean | null | void;
  onRestart?: (this: Battle, target: Pokemon, source: Pokemon, sourceEffect: Effect) => boolean | null | void;
  onEnd?: (this: Battle, target: Pokemon) => void;
  onBeforeMove?: VoidSourceMoveCallback;
  onBeforeTurn?: (this: Battle, pokemon: Pokemon) => void;
  onAfterMove?: VoidSourceMoveCallback;
  onAfterMoveSecondary?: VoidMoveCallback;
  onAfterMoveSecondarySelf?: VoidSourceMoveCallback;
  onDamage?: (
    this: Battle,
    damage: number,
    target: Pokemon,
    source: Pokemon,
    effect: Effect
  ) => number | boolean | null | void;
  onModifyMove?: (this: Battle, move: ActiveMove, pokemon: Pokemon, target: Pokemon | null) => void;
  onResidual?: (this: Battle, target: Pokemon, source: Pokemon, effect: Effect) => void;
  onSetStatus?: (
    this: Battle,
    status: ConditionData,
    target: Pokemon,
    source: Pokemon,
    effect: Effect
  ) => boolean | null | void;
  onSwitchIn?: (this: Battle, pokemon: Pokemon) => void;
  onSwitchOut?: (this: Battle, pokemon: Pokemon) => void;
  onTryHit?: ExtResultMoveCallback;
  onTryMove?: ResultSourceMoveCallback;
  onUpdate?: (this: Battle, pokemon: Pokemon) => void;
} & Partial<Record<\`on\${string}\`, GenericConditionCallback | boolean | number | string>>;

export type MoveEventMethods = {
  basePowerCallback?: (this: Battle, pokemon: Pokemon, target: Pokemon, move: ActiveMove) => number | false | null;
  beforeMoveCallback?: (this: Battle, pokemon: Pokemon, target: Pokemon | null, move: ActiveMove) => boolean | void;
  beforeTurnCallback?: (this: Battle, pokemon: Pokemon, target: Pokemon) => void;
  damageCallback?: (this: Battle, pokemon: Pokemon, target: Pokemon) => number | false;
  priorityChargeCallback?: (this: Battle, pokemon: Pokemon) => void;
  onDisableMove?: (this: Battle, pokemon: Pokemon) => void;
  onAfterHit?: VoidSourceMoveCallback;
  onAfterSubDamage?: (
    this: Battle,
    damage: number,
    target: Pokemon,
    source: Pokemon,
    move: ActiveMove
  ) => void;
  onAfterMoveSecondarySelf?: VoidSourceMoveCallback;
  onAfterMoveSecondary?: VoidMoveCallback;
  onAfterMove?: VoidSourceMoveCallback;
  onDamagePriority?: number;
  onDamage?: (
    this: Battle,
    damage: number,
    target: Pokemon,
    source: Pokemon,
    effect: Effect
  ) => number | boolean | null | void;
  onBasePower?: ModifierSourceMoveCallback;
  onEffectiveness?: (
    this: Battle,
    typeMod: number,
    target: Pokemon | null,
    type: string,
    move: ActiveMove
  ) => number | void;
  onHit?: ResultMoveCallback;
  onHitField?: ResultMoveCallback;
  onHitSide?: (this: Battle, side: Side, source: Pokemon, move: ActiveMove) => boolean | null | '' | void;
  onModifyMove?: (this: Battle, move: ActiveMove, pokemon: Pokemon, target: Pokemon | null) => void;
  onModifyPriority?: ModifierSourceMoveCallback;
  onMoveFail?: VoidMoveCallback;
  onModifyType?: (this: Battle, move: ActiveMove, pokemon: Pokemon, target: Pokemon) => void;
  onModifyTarget?: (
    this: Battle,
    relayVar: {target: Pokemon},
    pokemon: Pokemon,
    target: Pokemon,
    move: ActiveMove
  ) => void;
  onPrepareHit?: ResultMoveCallback;
  onTry?: ResultSourceMoveCallback;
  onTryHit?: ExtResultSourceMoveCallback;
  onTryHitField?: ResultMoveCallback;
  onTryHitSide?: (this: Battle, side: Side, source: Pokemon, move: ActiveMove) => boolean | null | '' | void;
  onTryImmunity?: ResultMoveCallback;
  onTryMove?: ResultSourceMoveCallback;
  onUseMoveMessage?: VoidSourceMoveCallback;
} & Partial<Record<\`on\${string}\`, GenericMoveCallback | number>> &
  Partial<Record<\`\${string}Callback\`, GenericMoveCallback>>;

export type MoveData = HitEffect &
  MoveEventMethods & {
    name: string;
    num?: number;
    condition?: ConditionData;
    basePower: number;
    accuracy: true | number;
    pp: number;
    category: MoveCategory;
    type: string;
    priority: number;
    target: MoveTarget;
    flags: MoveFlags;
    realMove?: string;
    damage?: number | 'level' | false | null;
    contestType?: string;
    noPPBoosts?: boolean;
    isZ?: boolean | string;
    zMove?: {
      basePower?: number;
      effect?: string;
      boost?: SparseBoostsTable;
    };
    isMax?: boolean | string;
    maxMove?: {
      basePower: number;
    };
    ohko?: boolean | string;
    thawsTarget?: boolean;
    heal?: [number, number] | null;
    forceSwitch?: boolean;
    selfSwitch?: SelfSwitchType;
    selfBoost?: {
      boosts?: SparseBoostsTable | null;
    };
    selfdestruct?: SelfdestructType;
    breaksProtect?: boolean;
    recoil?: [number, number];
    drain?: [number, number];
    mindBlownRecoil?: boolean;
    stealsBoosts?: boolean;
    struggleRecoil?: boolean;
    secondary?: SecondaryEffect | null;
    secondaries?: SecondaryEffect[] | null;
    self?: SecondaryEffect | null;
    hasSheerForce?: boolean;
    alwaysHit?: boolean;
    baseMoveType?: string;
    basePowerModifier?: number;
    critModifier?: number;
    critRatio?: number;
    overrideOffensivePokemon?: 'target' | 'source';
    overrideOffensiveStat?: StatIDExceptHP;
    overrideDefensivePokemon?: 'target' | 'source';
    overrideDefensiveStat?: StatIDExceptHP;
    forceSTAB?: boolean;
    ignoreAbility?: boolean;
    ignoreAccuracy?: boolean;
    ignoreDefensive?: boolean;
    ignoreEvasion?: boolean;
    ignoreImmunity?: boolean | Partial<Record<string, boolean>>;
    ignoreNegativeOffensive?: boolean;
    ignoreOffensive?: boolean;
    ignorePositiveDefensive?: boolean;
    ignorePositiveEvasion?: boolean;
    multiaccuracy?: boolean;
    multihit?: number | [number, number];
    multihitType?: string;
    noDamageVariance?: boolean;
    nonGhostTarget?: MoveTarget | string;
    pressureTarget?: MoveTarget | string;
    spreadModifier?: number;
    sleepUsable?: boolean;
    smartTarget?: boolean;
    tracksTarget?: boolean;
    willCrit?: boolean;
    hasCrashDamage?: boolean;
    isConfusionSelfHit?: boolean;
    noSketch?: boolean;
    stallingMove?: boolean;
    baseMove?: string;
    isNonstandard?: Nonstandard;
  };

export interface ActiveMove extends MoveData {
  readonly name: string;
  readonly effectType: 'Move';
  readonly id: ID;
  num: number;
  weather?: ID;
  status?: ID;
  hit: number;
  moveHitData?: Record<string, MoveHitData>;
  ability?: Ability;
  allies?: Pokemon[];
  auraBooster?: Pokemon;
  causedCrashDamage?: boolean;
  forceStatus?: ID;
  hasAuraBreak?: boolean;
  hasBounced?: boolean;
  hasSheerForce?: boolean;
  isExternal?: boolean;
  lastHit?: boolean;
  magnitude?: number;
  negateSecondary?: boolean;
  pranksterBoosted?: boolean;
  selfDropped?: boolean;
  spreadHit?: boolean;
  statusRoll?: string;
  stellarBoosted?: boolean;
  totalDamage?: number | false;
  typeChangerBoosted?: Effect;
  willChangeForme?: boolean;
  infiltrates?: boolean;
  isZOrMaxPowered?: boolean;
}

export interface Battle {
  readonly id: ID;
  readonly format: AnyObject;
  readonly formatData: EffectState;
  readonly gameType: GameType;
  readonly activePerHalf: 1 | 2 | 3;
  readonly field: Field;
  readonly sides: Side[];
  readonly prngSeed: readonly number[];
  readonly hints: Set<string>;
  readonly NOT_FAIL: '';
  readonly HIT_SUBSTITUTE: 0;
  readonly FAIL: false;
  readonly SILENT_FAIL: null;
  gen: number;
  rated: boolean | string;
  reportExactHP: boolean;
  reportPercentages: boolean;
  turn: number;
  midTurn: boolean;
  started: boolean;
  ended: boolean;
  winner?: string;
  effect: Effect;
  effectState: EffectState;
  event: AnyObject;
  activeMove: ActiveMove | null;
  activePokemon: Pokemon | null;
  activeTarget: Pokemon | null;
  lastMove: ActiveMove | null;
  lastSuccessfulMoveThisTurn: ID | null;
  lastDamage: number;
  trunc(num: number, bits?: number): number;
  clampIntRange(num: unknown, min?: number, max?: number): number;
  toID(text: unknown): ID;
  toJSON(): AnyObject;
  toString(): string;
  random(m?: number, n?: number): number;
  randomChance(numerator: number, denominator: number): boolean;
  sample<T>(items: readonly T[]): T;
  resetRNG(seed?: readonly number[] | null): void;
  suppressingAbility(target?: Pokemon): boolean | null | undefined;
  setActiveMove(move?: ActiveMove | null, pokemon?: Pokemon | null, target?: Pokemon | null): void;
  clearActiveMove(failed?: boolean): void;
  updateSpeed(): void;
  eachEvent(eventid: string, effect?: Effect | null, relayVar?: boolean): void;
  residualEvent(eventid: string, relayVar?: unknown): void;
  singleEvent(
    eventid: string,
    effect?: Effect | null,
    effectState?: EffectState | null,
    target?: Pokemon | Side | Field | null,
    source?: Pokemon | null,
    sourceEffect?: Effect | null,
    relayVar?: unknown
  ): unknown;
  runEvent(
    eventid: string,
    target?: Pokemon | Side | Field | null,
    source?: Pokemon | null,
    effect?: Effect | null,
    relayVar?: unknown,
    onEffect?: boolean,
    fastExit?: boolean
  ): unknown;
  priorityEvent(eventid: string, target?: Pokemon | Side | Field | null, source?: Pokemon | null, effect?: Effect | null, relayVar?: unknown): unknown;
  getPokemon(fullname: string | Pokemon): Pokemon | null;
  getPokemonById(pokemonId: string): Pokemon | null;
  getAllPokemon(): Pokemon[];
  getAllActive(): Pokemon[];
  canSwitch(side: Side): number;
  getRandomSwitchable(side: Side): Pokemon | null;
  swapPosition(pokemon: Pokemon, newPosition: number, attributes?: string): boolean;
  getAtSlot(slot: PokemonSlot | null): Pokemon | null;
  faint(pokemon: Pokemon, source?: Pokemon, effect?: Effect): void;
  boost(
    boost: SparseBoostsTable,
    target?: Pokemon | null,
    source?: Pokemon | null,
    effect?: Effect | null,
    isSecondary?: boolean,
    isSelf?: boolean
  ): boolean | null | 0;
  damage(
    damage: number,
    target?: Pokemon | null,
    source?: Pokemon | null,
    effect?: 'drain' | 'recoil' | Effect | null,
    instafaint?: boolean
  ): number | false | null | undefined;
  directDamage(damage: number, target?: Pokemon, source?: Pokemon | null, effect?: Effect | null): number | false;
  heal(
    damage: number,
    target?: Pokemon,
    source?: Pokemon | null,
    effect?: 'drain' | Effect | null
  ): number | false | null | undefined;
  chain(previousMod: number | [number, number], nextMod: number | [number, number]): number;
  chainModify(numerator: number | [number, number], denominator?: number): number;
  modify(value: number, numerator: number | [number, number], denominator?: number): number;
  finalModify(relayVar: number): number;
  getCategory(move: string | ActiveMove): MoveCategory;
  randomizer(baseDamage: number): number;
  validTargetLoc(targetLoc: number, source: Pokemon, targetType: string): boolean;
  validTarget(target: Pokemon, source: Pokemon, targetType: string): boolean;
  getTarget(pokemon: Pokemon, move: string | ActiveMove, targetLoc: number, originalTarget?: Pokemon): Pokemon;
  getRandomTarget(pokemon: Pokemon, move: string | ActiveMove): Pokemon | null;
  checkFainted(): boolean;
  updatePP(): void;
  hint(hint: string, once?: boolean, side?: Side): void;
  add(...parts: unknown[]): void;
  addMove(...parts: unknown[]): void;
  attrLastMove(...parts: unknown[]): void;
  retargetLastMove(newTarget: Pokemon): void;
  debug(activity: string): void;
  debugError(activity: string): void;
}

export interface Side {
  readonly battle: Battle;
  readonly id: SideID;
  readonly n: number;
  name: string;
  avatar: string;
  foe: Side;
  allySide: Side | null;
  team: AnyObject[];
  pokemon: Pokemon[];
  active: Pokemon[];
  pokemonLeft: number;
  zMoveUsed: boolean;
  dynamaxUsed: boolean;
  faintedLastTurn: Pokemon | null;
  faintedThisTurn: Pokemon | null;
  totalFainted: number;
  lastSelectedMove: ID;
  sideConditions: Record<string, EffectState>;
  slotConditions: Array<Record<string, EffectState>>;
  activeRequest: AnyObject | null;
  choice: Choice;
  lastMove: ActiveMove | null;
  readonly requestState: RequestState;
  toJSON(): AnyObject;
  canDynamaxNow(): boolean;
  getChoice(): string;
  toString(): string;
  getRequestData(forAlly?: boolean): AnyObject;
  randomFoe(): Pokemon | null;
  foeSidesWithConditions(): Side[];
  foePokemonLeft(): number;
  allies(all?: boolean): Pokemon[];
  foes(all?: boolean): Pokemon[];
  activeTeam(): Pokemon[];
  hasAlly(pokemon: Pokemon): boolean;
  addSideCondition(status: string | Effect, source?: Pokemon | null, sourceEffect?: Effect | null): boolean | null;
  getSideCondition(status: string | Effect): Effect | null;
  getSideConditionData(status: string | Effect): AnyObject;
  removeSideCondition(status: string | Effect): boolean;
  addSlotCondition(target: Pokemon | number, status: string | Effect, source?: Pokemon | null, sourceEffect?: Effect | null): boolean | null;
  getSlotCondition(target: Pokemon | number, status: string | Effect): Effect | null;
  removeSlotCondition(target: Pokemon | number, status: string | Effect): boolean;
  send(...parts: unknown[]): void;
  emitRequest(update: AnyObject): void;
  emitChoiceError(message: string, unavailable?: boolean): boolean;
  isChoiceDone(): boolean;
  clearChoice(): void;
  choose(input: string): boolean | Side;
  choosePass(): boolean | Side;
  autoChoose(): boolean | Side;
  destroy(): void;
}

export interface Pokemon {
  readonly side: Side;
  readonly battle: Battle;
  readonly set: AnyObject;
  readonly name: string;
  readonly fullname: string;
  readonly level: number;
  readonly gender: GenderName;
  readonly happiness: number;
  readonly pokeball: string;
  readonly dynamaxLevel: number;
  readonly gigantamax: boolean;
  readonly baseHpType: string;
  readonly baseHpPower: number;
  readonly baseMoveSlots: MoveSlot[];
  moveSlots: MoveSlot[];
  hpType: string;
  hpPower: number;
  position: number;
  details: string;
  uuid: string;
  baseSpecies: Species;
  species: Species;
  speciesState: EffectState;
  status: ID;
  statusState: EffectState;
  volatiles: Record<string, EffectState>;
  showCure?: boolean;
  baseStoredStats: StatsTable;
  storedStats: StatsExceptHPTable;
  boosts: BoostsTable;
  alphaBoosts: BoostsTable;
  baseAbility: ID;
  ability: ID;
  abilityState: EffectState;
  item: ID;
  itemState: EffectState;
  lastItem: ID;
  usedItemThisTurn: boolean;
  ateBerry: boolean;
  trapped: boolean | 'hidden';
  maybeTrapped: boolean;
  maybeDisabled: boolean;
  illusion: Pokemon | null;
  transformed: boolean;
  maxhp: number;
  baseMaxhp: number;
  hp: number;
  fainted: boolean;
  faintQueued: boolean;
  subFainted: boolean | null;
  types: string[];
  addedType: string;
  knownType: boolean;
  apparentType: string;
  switchFlag: ID | boolean;
  forceSwitchFlag: boolean;
  skipBeforeSwitchOutEventFlag: boolean;
  draggedIn: number | null;
  newlySwitched: boolean;
  beingCalledBack: boolean;
  lastMove: ActiveMove | null;
  lastMoveEncore?: ActiveMove | null;
  lastMoveUsed: ActiveMove | null;
  lastMoveTargetLoc?: number;
  moveThisTurn: string | boolean;
  statsRaisedThisTurn: boolean;
  statsLoweredThisTurn: boolean;
  moveLastTurnResult: boolean | null | undefined;
  moveThisTurnResult: boolean | null | undefined;
  hurtThisTurn: number | null;
  lastDamage: number;
  attackedBy: Array<{
    source: Pokemon;
    damage: number;
    thisTurn: boolean;
    move?: ID;
    slot: PokemonSlot;
    damageValue?: number | boolean;
  }>;
  timesAttacked: number;
  isActive: boolean;
  activeTurns: number;
  activeMoveActions: number;
  previouslySwitchedIn: number;
  truantTurn: boolean;
  swordBoost: boolean;
  shieldBoost: boolean;
  syrupTriggered: boolean;
  stellarBoostedTypes: string[];
  isStarted: boolean;
  duringMove: boolean;
  weighthg: number;
  speed: number;
  abilityOrder: number;
  canMegaEvo: string | null | undefined;
  canUltraBurst: string | null | undefined;
  readonly canGigantamax: string | null;
  canTerastallize?: string | null;
  terastallized?: string | null;
  pendingStaleness?: string;
  getHealth: () => HealthDisplay;
  toJSON(): AnyObject;
  getSlot(): PokemonSlot;
  toString(): string;
  updateSpeed(): void;
  calculateStat(statName: StatIDExceptHP, boost: number, modifier?: number, statUser?: Pokemon): number;
  getStat(statName: StatIDExceptHP, unboosted?: boolean, unmodified?: boolean): number;
  getActionSpeed(): number;
  getBestStat(unboosted?: boolean, unmodified?: boolean): StatIDExceptHP;
  getCombatPower(): number;
  getWeight(): number;
  getMoveData(move: string | ActiveMove): MoveSlot | null;
  getMoveHitData(move: ActiveMove): MoveHitData | null;
  alliesAndSelf(): Pokemon[];
  allies(): Pokemon[];
  adjacentAllies(): Pokemon[];
  foes(all?: boolean): Pokemon[];
  adjacentFoes(): Pokemon[];
  isAlly(pokemon: Pokemon | null): boolean;
  isAdjacent(pokemon: Pokemon): boolean;
  getUndynamaxedHP(amount?: number): number;
  getSmartTargets(target: Pokemon, move: ActiveMove): Pokemon[];
  getAtLoc(targetLoc: number): Pokemon | null;
  getLocOf(target: Pokemon): number;
  getMoveTargets(move: ActiveMove, target: Pokemon): {targets: Pokemon[]; pressureTargets: Pokemon[]};
  ignoringAbility(): boolean;
  ignoringItem(): boolean;
  deductPP(move: string | ActiveMove, amount?: number | null, target?: Pokemon | null | false): number;
  moveUsed(move: ActiveMove, targetLoc?: number): void;
  gotAttacked(move: string | ActiveMove, damage: number | false | undefined, source: Pokemon): void;
  getLastAttackedBy(): {source: Pokemon; damage: number; thisTurn: boolean; move?: ID; slot: PokemonSlot; damageValue?: number | boolean} | undefined;
  getLastDamagedBy(filterOutSameSide: boolean): {source: Pokemon; damage: number; thisTurn: boolean; move?: ID; slot: PokemonSlot; damageValue?: number | boolean} | undefined;
  getLockedMove(): string | null;
  getMoves(lockedMove?: string | null, restrictData?: boolean): Array<{
    move: string;
    id: ID;
    pp: number;
    maxpp: number;
    target?: string;
    disabled?: boolean | string;
    disabledSource?: string;
  }>;
  maxMoveDisabled(baseMove: ActiveMove | string): boolean;
  getDynamaxRequest(skipChecks?: boolean): AnyObject | undefined;
  getMoveRequestData(): AnyObject;
  getSwitchRequestData(forAlly?: boolean): AnyObject;
  isLastActive(): boolean;
  positiveBoosts(): number;
  getCappedBoost(boosts: SparseBoostsTable): SparseBoostsTable;
  boostBy(boosts: SparseBoostsTable): number;
  clearBoosts(): void;
  setBoost(boosts: SparseBoostsTable): void;
  copyVolatileFrom(pokemon: Pokemon, switchCause?: string | boolean): boolean;
  transformInto(pokemon: Pokemon, effect?: Effect): boolean;
  setSpecies(rawSpecies: Species, source?: Effect | null, isTransform?: boolean): boolean;
  formeChange(speciesId: string | Species, source?: Effect, isPermanent?: boolean, message?: string): boolean;
  clearVolatile(includeSwitchFlags?: boolean): void;
  hasType(type: string | string[]): boolean;
  faint(source?: Pokemon | null, effect?: Effect | null): number;
  capture(): void;
  damage(d: number, source?: Pokemon | null, effect?: Effect | null): number;
  tryTrap(isHidden?: boolean): boolean;
  hasMove(moveid: string): string | false;
  disableMove(moveid: string, isHidden?: boolean | string, sourceEffect?: Effect): void;
  heal(d: number, source?: Pokemon | null, effect?: Effect | null): number | false;
  sethp(d: number): number | undefined;
  trySetStatus(status: string | ConditionData, source?: Pokemon | null, sourceEffect?: Effect | null): boolean;
  cureStatus(silent?: boolean): boolean;
  setStatus(status: string | ConditionData, source?: Pokemon | null, sourceEffect?: Effect | null, ignoreImmunities?: boolean): boolean;
  updatePP(): void;
  clearStatus(): boolean;
  getStatus(): ConditionData;
  eatItem(force?: boolean, source?: Pokemon, sourceEffect?: Effect): boolean;
  useItem(source?: Pokemon, sourceEffect?: Effect): boolean;
  takeItem(source?: Pokemon): Item | false;
  setItem(item: string | Item, source?: Pokemon, effect?: Effect): boolean;
  getItem(): Item;
  hasItem(item: string | string[]): boolean;
  clearItem(): boolean;
  setAbility(ability: string | Ability, source?: Pokemon | null, isFromFormeChange?: boolean, isTransform?: boolean): ID | boolean | null;
  getAbility(): Ability;
  hasAbility(ability: string | string[]): boolean;
  clearAbility(): ID | boolean | null;
  getNature(): Nature;
  addVolatile(status: string | ConditionData, source?: Pokemon | null, sourceEffect?: Effect | null, linkedStatus?: string | ConditionData | null): boolean | unknown;
  getVolatile(status: string | Effect): Effect | null;
  removeVolatile(status: string | Effect): boolean;
  removeLinkedVolatiles(linkedStatus: string | Effect, linkedPokemon: Pokemon[]): void;
  setType(newType: string | string[], enforce?: boolean): boolean;
  addType(newType: string): boolean;
  getTypes(excludeAdded?: boolean, preterastallized?: boolean): string[];
  isGrounded(negateImmunity?: boolean): boolean;
  isSemiInvulnerable(): boolean;
  isSkyDropped(): boolean;
  isProtected(): boolean;
  effectiveWeather(): ID | '';
  runEffectiveness(move: ActiveMove): number;
  runImmunity(type: string, message?: string | boolean): boolean;
  runStatusImmunity(type: string, message?: string): boolean;
  destroy(): void;
}
`;
