export const WORKSPACE_ABILITY_TYPES_PATH =
  '.cobblemon-schema-tools/ability-types.d.ts';

export const WORKSPACE_ABILITY_TYPES_CONTENT = `// Generated by Cobblemon Schema Tools.
// This file is only needed when "Use Typescript for Abilities?" is enabled.

export type AbilityCallback = (this: any, ...args: any[]) => unknown;
export type AbilityCallbackValue =
  | AbilityCallback
  | number
  | boolean
  | string;

export interface AbilityFlags {
  breakable?: 1;
  cantsuppress?: 1;
  failroleplay?: 1;
  failskillswap?: 1;
  noentrain?: 1;
  noreceiver?: 1;
  notrace?: 1;
  notransform?: 1;
}

export type AbilityConditionData = {
  duration?: number;
  noCopy?: boolean;
} & Partial<Record<\`on\${string}\`, AbilityCallbackValue>>;

export type AbilityData = {
  name: string;
  num: number;
  rating: number;
  flags: AbilityFlags;
  suppressWeather?: true;
  isNonstandard?: string;
  condition?: AbilityConditionData;
} & Partial<Record<\`on\${string}\`, AbilityCallbackValue>>;
`;
